language: objective-c
osx_image: xcode8
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7"          SCHEME="GCDKit iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="GCDKit iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="GCDKit iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="GCDKit iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="GCDKit iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="GCDKit iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="arch=x86_64"                    SCHEME="GCDKit OSX"     SDK=macosx10.12          RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="GCDKit watchOS" SDK=watchsimulator3.0    RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="GCDKit tvOS"    SDK=appletvsimulator10.0 RUN_TESTS="YES" POD_LINT="NO"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - if [ $RUN_TESTS == "YES" ]; then 
      xcodebuild -project GCDKit.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c; 
      xcodebuild -project GCDKit.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c;  
    fi
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
